version: "3"

services:
  checkout:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./demo/checkout
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./demo/checkout:/app
    # networks:
    #   - proxynet
# networks:
#   proxynet:
#     external:
#       name: custom_network
