version: "3.5"

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: verdaccio
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    networks:
      - proxynet

networks:
  proxynet:
    name: custom_network
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
